name: mvar-lock
version: 0.1.0.0
category: Concurrency

synopsis: >
  A trivial lock based on MVar.

description: >
  Using an MVar as a lock is a common pattern. This module just wraps that up
  into some functions with nice names that make the pattern explicit.

author:     Chris Martin <ch.martin@gmail.com>
maintainer: Chris Martin <ch.martin@gmail.com>

homepage: https://github.com/chris-martin/haskell-libraries

license:      Apache-2.0
license-file: license.txt

library:
  source-dirs: src
  exposed-modules:
    - Control.Concurrent.MVarLock

dependencies:
  - base >= 4.9 && < 4.10
  - safe-exceptions

ghc-options:
  - -Wall

default-extensions:
  - NoImplicitPrelude
