name: bad-twenty-four
version: 0.1.0.0

author:     Chris Martin <ch.martin@gmail.com>
maintainer: Chris Martin <ch.martin@gmail.com>

homepage: https://github.com/chris-martin/haskell-libraries

library:
  source-dirs: src
  exposed-modules:
    - Puzzle.BadTwentyFour

dependencies:
  - base >= 4.9 && < 4.10
  - containers
  - multiset

ghc-options:
  - -Wall

tests:
  doctest:
    source-dirs: test
    main: doctest.hs
    dependencies:
      - bad-twenty-four
      - doctest
