name: atomic-modify
version: 0.1.0.0
category: Concurrency

synopsis: >
  A typeclass for mutable references that have an atomic modify operation.

description: >
  A typeclass for mutable references that have an atomic modify operation.
  Generalizes atomic modify operations in IO and STM contexts for IORef,
  MVar, TVar, and TMVar.

author:     Chris Martin <ch.martin@gmail.com>
maintainer: Chris Martin <ch.martin@gmail.com>

homepage: https://github.com/chris-martin/haskell-libraries

license:      Apache-2.0
license-file: license.txt

library:
  source-dirs: src
  exposed-modules:
    - Control.Concurrent.AtomicModify

dependencies:
  - base >= 4.9 && < 4.10
  - stm

ghc-options:
  - -Wall

default-extensions:
  - NoImplicitPrelude
