name: num-qq
version: 0.1.0.0
category: Numerical

library:
  source-dirs: src
  exposed-modules:
    - Num.QQ

author:     Chris Martin <ch.martin@gmail.com>
maintainer: Chris Martin <ch.martin@gmail.com>

homepage: https://github.com/chris-martin/haskell-libraries

license:      Apache-2.0
license-file: license.txt

dependencies:
  - base >= 4.9 && < 4.10
  - template-haskell

ghc-options:
  - -Wall

default-extensions:
  - NoImplicitPrelude

tests:
  doctest:
    source-dirs: test
    main: doctest.hs
    dependencies:
      - doctest
      - num-qq
    ghc-options:
      - -threaded
